import Head from 'next/head';
// import 'tailwindcss/tailwind.css';
import '../styles/globals.css';

function MyApp({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>Jonas Folio - Shopify Theme Developer</title>
				<meta name='description' content='Generated by create next app' />
				<meta
					name='keywords'
					content='shopify, shopify theme dev, shopify theme, shopify theme developer, shopify theme development, theme development, portfolio, shopify portfolio, shopify theme portfolio'
				/>
				<link
					rel='preload'
					href='/fonts/ExtraboldItalic.woff2'
					as='font'
					crossOrigin=''
				/>
				<link
					rel='preload'
					href='/fonts/Regular.woff2'
					as='font'
					crossOrigin=''
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Component {...pageProps} />
		</>
	);
}

export default MyApp;
